name: Run clockwork tests and build containers

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
      - github_actions
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up mysql
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
        user: test_user
        password: test_password


    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt upgrade && sudo apt-get install -y \
          build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          pkg-config \
          debootstrap \
          debian-keyring \
          debian-archive-keyring \
          rsync

    - name: Install Singularity
      env:
        SINGULARITY_VERSION: 3.5.3
        GOPATH: /tmp/go
      run: |
        mkdir -p $GOPATH
        sudo mkdir -p /usr/local/var/singularity/mnt
        mkdir -p $GOPATH/src/github.com/sylabs
        cd $GOPATH/src/github.com/sylabs
        wget https://github.com/hpcng/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz
        tar -xzf singularity-${SINGULARITY_VERSION}.tar.gz
        cd singularity
        ./mconfig -v -p /usr/local
        make -j `nproc 2>/dev/null || echo 1` -C ./builddir all
        sudo make -C ./builddir install


    - name: Check out code for the container build
      uses: actions/checkout@v2

    - name: Set release version if is a release
      if: startsWith(github.event.ref, 'refs/tags/v')
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set release version if not a release
      if: false == startsWith(github.event.ref, 'refs/tags/v')
      run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV

    - name: Run tests
      run: |
        sudo ./scripts/install_dependencies.sh /bioinf-tools
        export PATH=/bioinf-tools/:/bioinf-tools/cortex/bin/:/bioinf-tools/cortex/scripts/analyse_variants/seq-align/bin/:/bioinf-tools/vcftools-0.1.15/install/bin:/bioinf-tools/enaBrowserTools/python3:/clockwork/scripts/:$PATH
        export PERL5LIB=/bioinf-tools/vcftools-0.1.15/install/share/perl/5.30.0/:/bioinf-tools/cortex/scripts/analyse_variants/bioinf-perl/lib:/bioinf-tools/cortex/scripts/calling/:$PERL5LIB
        export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        cd python
        python3 setup.py test

    - name: Build Singularity container
      env:
        SINGULARITY_RECIPE: Singularity.def
        OUTPUT_CONTAINER: clockwork_${{env.RELEASE_VERSION}}.img
      run: |
        ls
        if [ -f "${SINGULARITY_RECIPE}" ]; then
            sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
        else
            echo "${SINGULARITY_RECIPE} is not found."
            echo "Present working directory: $PWD"
            ls
        fi

    - name: Release
      if: startsWith(github.event.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: clockwork*.img
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

